# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app(scheme: "DMFastlane",
            workspace: "DMFastlane.xcworkspace",
            configuration: "Debug",
            export_method: "development",
            output_directory: "~/Desktop/", # Destination directory. Defaults to current directory.
            output_name: "DMFastlane.ipa"       # specify the name of the .ipa file to generate (including file extension)
            )
  end
end
