# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
def sharePods
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry', '~> 1.0.2'
end
target 'DMFastlane' do

  sharePods
  
  target 'DMFastlaneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DMFastlaneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
